name: Build Image
on:
  push:
    branches:
      - main
    paths:
      - 'Makefile'
      - 'Dockerfile'
      - 'telegramDockerSDK.py'
      - 'requirements.txt'
      - '.github/workflows/deploy.yml'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build multi-arch and push
      run: make ciDeploy
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}